# Setup
title: Alins Blog
url: https://alins.ir
paginate: 1
paginate_path: "/page:num/"
baseurl: "/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag


exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed


# Google Analytics
ga_analytics: G-HLWRB447XT

author:
  name: Alins
  url: https://twitter.com/alins1r
  email: alins.ir@yahoo.com

version: 1.0.0

nav:
  - title: WriteUp
    url: /alins/archive

  - title: About
    url: /alins/about
